apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: da-server
  name: da-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: da-server
  strategy: {}
  template:
    metadata:
      labels:
        app: da-server
    spec:
      containers:
        - env:
            - name: CLICKHOUSE_HOST
              value: clickhouse-server
            - name: CLICKHOUSE_KAFKA_HOSTS
              value: kafka:9092
            - name: IS_PRO
              value: "true"
            - name: KAFKA_HOSTS
              value: kafka:9092
            - name: REDIS_URL
              value: redis://redis:6379/0
          image: featbit/featbit-data-analytics-server:latest
          name: da-server
          ports:
            - containerPort: 80
          resources: 
            requests:
              memory: 512Mi
              cpu: 500m
              ephemeral-storage: 2Gi 
            limits:
              memory: 2Gi
              cpu: 500m
              ephemeral-storage: 4Gi 
      restartPolicy: Always
status: {}
